name: "anisf.dockerfiles.gke"

on:
  push:
    paths:
      - '**'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
        - v1.19.0
        - v1.20.0
        - v1.21.0
        - v1.22.0
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build GKE base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./Dockerfile
          tags: 'anisfathallah/gke:${{ matrix.kubectl_version }}-base'
          target: base
          build-args: |
            KUBECTL_VERSION=${{ matrix.kubectl_version }}

      - name: Test GKE base image
        uses: addnab/docker-run-action@v1
        with:
          image: 'anisfathallah/gke:${{ matrix.kubectl_version }}-base'
          options: -v ${{ github.workspace }}:/workspace
          run: |
            id
            cd /workspace
            echo $PATH
            gcloud version
            helm version
            kubectl version --client

      - name: Push GKE base image
        id: docker_push_base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: 'anisfathallah/gke:${{ matrix.kubectl_version }}-base'
          target: base
          build-args: |
            KUBECTL_VERSION=${{ matrix.kubectl_version }}

      - name: Build GKE stable image
        id: docker_build_stable
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./Dockerfile
          tags: 'anisfathallah/gke:${{ matrix.kubectl_version }}-stable'
          target: stable
          build-args: |
            KUBECTL_VERSION=${{ matrix.kubectl_version }}

      - name: Test GKE stable image
        uses: addnab/docker-run-action@v1
        with:
          image: 'anisfathallah/gke:${{ matrix.kubectl_version }}-stable'
          options: -v ${{ github.workspace }}:/workspace
          run: |
            id
            cd /workspace
            echo $PATH
            gcloud version
            helm version
            kubectl version --client

      - name: Push GKE stable image
        id: docker_push_stable
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: 'anisfathallah/gke:${{ matrix.kubectl_version }}-stable'
          target: stable
          build-args: |
            KUBECTL_VERSION=${{ matrix.kubectl_version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'anisfathallah/gke:${{ matrix.kubectl_version }}-stable'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'